# Generated by Django 4.0.3 on 2022-04-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
    ]
